language: minimal
services:
    - docker
stages:
  - name: deploy
    if: branch == master AND type = push
jobs:
  include:
    - stage: deploy
      script:
        - echo "$DOCKER_API_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - export APACHE_REPO=madhus2087/apache-proxy
        - docker build -f apache-oidc/Dockerfile -t $APACHE_REPO:build-$TRAVIS_BUILD_NUMBER .
        - docker push $APACHE_REPO
